### PR TITLE
Add guide for MIUI users

### PR DESCRIPTION
**Pull request by Naymmmm**
MIUI hates split apk's, I added a guide to help people that despise MIUI's split apk nonsense.

### CODE REVIEW

**Comment by amsryq** [comment]
IMO this should be within Bunny Manager, like some sort of a warning before installing.
I'm also a MIUI user here, installing split apks seems fine. Perhaps because I have MIUI optimizations turned off.

**Comment by amsryq** [comment]
Closing this PR since it is outside of repo scope(?), but thank you for the information that Shizuku could be an alternative method for MIUI users

**Comment by dxcvvxd** [comment]
step 1: install a custom rom🥱

**Comment by Naymmmm** [comment]
> step 1: install a custom rom🥱

step 2: brick phone or fail to unlock bootloader 🥱

**Comment by Rico040** [comment]
> > step 1: install a custom rom🥱
> 
> step 2: brick phone or fail to unlock bootloader 🥱

step 3: buy non-ximi phone 🥱

**Comment by Naymmmm** [comment]
> > > step 1: install a custom rom🥱
> > 
> > step 2: brick phone or fail to unlock bootloader 🥱
> 
> step 3: buy non-ximi phone 🥱

step 4: stop saying ximi 🥱

**Comment by ghost** [comment]
> > > > step 1: install a custom rom🥱
> > > 
> > > step 2: brick phone or fail to unlock bootloader 🥱
> > 
> > step 3: buy non-ximi phone 🥱
> 
> step 4: stop saying ximi 🥱

urghhh i-it's actually called Xiaomi ☝🏻🤓🤓

**Comment by nyxiereal** [comment]
> > > > > step 1: install a custom rom🥱
> > > > 
> > > > 
> > > > step 2: brick phone or fail to unlock bootloader 🥱
> > > 
> > > 
> > > step 3: buy non-ximi phone 🥱
> > 
> > 
> > step 4: stop saying ximi 🥱
> 
> urghhh i-it's actually called Xiaomi ☝🏻🤓🤓

It's ximi you dingus 🤤

**Pull request closed without merging**
