### PR TITLE
Alternative non-root install method

### PR DESCRIPTION
**Pull request by radioaddition**
Add documentation for an alternative rootless install using LSPatch for those struggling with the Vendetta Manager method like myself

### CODE REVIEW

**Comment by ghost** [comment]
this is harder and more complicated than the current method

**Comment by amsryq** [comment]
LSPatch project has been archived and theoretically wouldn't work with Android 14 QPR2 and above.

The non-root installation method stated in the README is only temporary, and we're working on making it better. And as pointed out, this looks even more complicated than the temporary solution.

**Comment by radioaddition** [comment]
only reason this was proposed is that I (and from a quick scan of the issues others as well) am struggling with the vendetta manager method either installing and refusing to launch (my personal issue), or just refusing to work at all. This is meant only as a backup to the current solution, and while I agree it's definitely more complicated, it at least adds an alternative in case the current one fails. anyways, I'm currently running it on android 14 and the fact that lspatch is archived hasn't given me any issues. I can update it again to include a disclaimer regarding only using if the above method doesn't work

**Comment by amsryq** [comment]
Apologies, I just didn't want another complicated solution within the readme. People would ask about it in support channel and I'd rather not deal with it. We have BunnyManager now (94d6c0ea392c81ce147c4105e6b0da35d884f54e). I appreciate your effort, though

**Pull request closed without merging**
