### PR TITLE
Use a sheet instead of a popup for plugin/theme installation

### PR DESCRIPTION
**Pull request by notmarek**
fix: Use a sheet instead of a popup for plugin/theme installation popup (this fixes issues on older versions and also matches the popup with the font install popup)

### CODE REVIEW

**Comment by notmarek** [comment]
IMG_2010

**Comment by saberana** [comment]
I installed 215.24 stable version and have this. Did branch merged into official or not?
image

**Comment by notmarek** [comment]
It is not merged you can use my plugin in the meantime https://plugins.notmarek.com/224compat (source at https://GitHub.com/NotMarek/bunny-plugins) to install it use `/eval bunny.plugins.fetchPlugin("https://plugins.notmarek.com/224compat")`  (you will first need to enable developer settings and eval inside them)

**Comment by saberana** [comment]
> It is not merged you can use my plugin in the meantime https://plugins.notmarek.com/224compat (source at https://GitHub.com/NotMarek/bunny-plugins) to install it use `/eval bunny.plugins.fetchPlugin("https://plugins.notmarek.com/224compat")` (you will first need to enable developer settings and eval inside them)

Thanks for response! But for some reason i get this. 
`TypeError: undefined is not a function`
    `at global (JavaScript:1:26)`
    `at eval (native)`
    `at ?anon_0_ (bunny:2:31033)`
    `at next (native)`
    `at uu (bunny:1:1048)`
    `at u (bunny:1:1247)`
    `at anonymous (bunny:1:1307)`
    `at tryCallTwo (/tmp/tmp7p868pi8/ReactAndroid/hermes-engine/.cxx/MinSizeRel/3g3ur182/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:9)`
    `at doResolve (/tmp/tmp7p868pi8/ReactAndroid/hermes-engine/.cxx/MinSizeRel/3g3ur182/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:25)`
    `at Promise (/tmp/tmp7p868pi8/ReactAndroid/hermes-engine/.cxx/MinSizeRel/3g3ur182/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:14)`
    `at anonymous (bunny:1:1197)`
    `at execute (bunny:2:31179)`
    `at apply (native)`
    `at anonymous (bunny`:1:2207)
    `at apply (native)`
    `at anonymous (bunny`:4:1013)
    `at call (native)`
    `at anonymous (bunn`y:1:2152)
    `at apply (native)`
    `at td (bunny:1:2213`)
    `at f (bunny:1:2927)`
    `at apply (bunny:1:2994)`
    `at proxy trap (native)`
    `at ?anon_0_ (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:5392:6033)`
    `at next (native)`
    `at asyncGeneratorStep (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:25:87)`
    `at _next (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:25:338)`
    `at tryCallOne (/tmp/tmp7p868pi8/ReactAndroid/hermes-engine/.cxx/MinSizeRel/3g3ur182/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)`
    `at anonymous (/tmp/tmp7p868pi8/ReactAndroid/hermes-engine/.cxx/MinSizeRel/3g3ur182/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)`
    `at apply (native)`
    `at anonymous (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:166:2034)`
    `at _callTimer (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:166:575)`
    `at _callReactNativeMicrotasksPass (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:166:1017)`
    `at callReactNativeMicrotasks (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:166:3831)`
    `at __callReactNativeMicrotasks (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:49:3309)`
    `at anonymous (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:49:1164)`
    `at __guard (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:49:2908)`
    `at flushedQueue (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:49:1122)`
    `at callFunctionReturnFlushedQueue (/workdir/discord_android_rn/android/app/src/main/assets/index.android.bundle:49:853)`
    `at apply (native)`
    `at td (bunny:1:2024)`
    `at f (bunny:1:2927)`
    `at apply (bunny:1:2994)`
    `at proxy trap (native)`

**Comment by notmarek** [comment]
Sorry meant vendetta.plugins.fetchPlugin

**Comment by saberana** [comment]
> Sorry meant vendetta.plugins.fetchPlugin
Sadly its gives crashes when open Plugins section on my version 215.24. ;[

**Comment by notmarek** [comment]
Huh that's weird :( I've only tested it in 224

**Comment by amsryq** [comment]
closing in favor of https://github.com/pyoncord/Bunny/commit/ad6524772b9dd98f36b640b8fba2d36e2d6a7f2b

**Pull request closed without merging**
